# Generated by Django 4.2.7 on 2024-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=10)),
                ('productprice', models.IntegerField()),
                ('productdiscription', models.CharField(max_length=10)),
                ('productimage', models.ImageField(upload_to='productimage')),
            ],
        ),
    ]
