# Generated by Django 4.2.7 on 2024-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=10)),
                ('categoryimage', models.ImageField(upload_to='categoryimage')),
                ('categorydiscription', models.CharField(max_length=10)),
            ],
        ),
    ]
