# Generated by Django 4.2.7 on 2024-03-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_products_productdiscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CONTACT',
        ),
    ]
