# Generated by Django 4.2.7 on 2024-03-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoryname',
            new_name='category',
        ),
    ]
