# Generated by Django 4.2.7 on 2024-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('EmailAddress', models.CharField(max_length=10)),
                ('phonenumber', models.IntegerField()),
                ('Address', models.CharField(max_length=10)),
            ],
        ),
    ]
