# Generated by Django 4.2.7 on 2024-02-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
    ]
